### ISSUE TITLE
Add direct link to download on Firefox

### ISSUE THREAD

**Issue by Naereen** [FreeTubeApp/freetube-redirect#1]
This link, https://addons.mozilla.org/en-US/firefox/addon/freetube-redirect/, seems to work, so it could be added to the README.md right?

**Comment by PrestonN** [comment]
Yes, you are correct.  I haven't had too much time lately and it was simply something that I have forgotten about.  I have added the links to this repo and I will have them on the main repo shortly.

**Comment by Naereen** [comment]
Hi, no problem, thanks for your fast reply!
