### ISSUE TITLE
Won't work with latest Beta of FreeTube

### ISSUE THREAD

**Issue by squinonescolon** [FreeTubeApp/freetube-redirect#12]
I installed version 0.8.0 Beta and when clicking on youtube links now nothing happens.

**Comment by PrestonN** [comment]
This now works with the latest dev builds of FreeTube.  We post automated builds [here](https://github.com/FreeTubeApp/FreeTube/actions?query=workflow%3ABuild) that you can download and test before the next full release.  If you have any issues with these builds then please let me know.
