### ISSUE TITLE
0.9.0 release notes says it works again, but it doesn't - atleast on Mac

### ISSUE THREAD

**Issue by timharek** [FreeTubeApp/freetube-redirect#13]
I'm still getting the "same" bug whenever I try to open a video with `freetube://` with and without the extention to Firefox. Is there anything we should add to our settings, to make this work properly?

**Comment by PrestonN** [comment]
Mac is difficult for me to test because I don't have a device to test with.  I'll have to setup a VM to figure out what's going on.  Can you please describe what the "Bug" is that you're experiencing?  Is it similar to [#618](https://github.com/FreeTubeApp/FreeTube/issues/618)?

**Comment by timharek** [comment]
Sorry, but I didn't get as many details in as in [#618](https://github.com/FreeTubeApp/FreeTube/issues/618). But yes, it seems like it is the same case for me, I'm also using 0.9.0.

Would also like to say thank you for creating this project!

**Comment by PrestonN** [comment]
Going to close this here because this is an issue with FreeTube itself and not the extension
