### ISSUE TITLE
Popup everytime I click a Youtube link

### ISSUE THREAD

**Issue by JamesLahey** [FreeTubeApp/freetube-redirect#16]
Every time I click a youtube link, I get a popup that says
"Allow this site to open the freetube link with Freetube?"
Choose a different application

and then 2 buttons that say [open link] and [cancel]
I am using the newest Firefox.
Anyway to make it so I don't have to click [open link] each time ?

**Comment by PrestonN** [comment]
I've noticed this recently. It wasn't happening before so I have to guess that it has to do with an update to Firefox that's forcing this. Is your Firefox instance setup to delete cache / cookies on restart? That might be what's causing it if I had to guess.

Either way, I don't think this is something I can fix, so I'm going to close.

Also, please consider using Privacy Redirect instead. They support redirecting to FreeTube along with other nice features and it's more actively developed than this extension is. This issue still persists with that extension however.
