### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by rm-rf-home** [FreeTubeApp/freetube-redirect#6]
It opens FreeTube but not the video. If FreeTube is closed while clicking a YouTube link, it opens FreeTube's "Latest Subscriptions" page. If FreeTube is already opened while clicking a link in the browser, it just brings FreeTube to the foreground but whatever was there just stays.

Firefox: 65.0.1 (64-Bit)
macOS: 10.14.3 (18D109)
MacBook Pro: Retina, 15-inch, Mid 2014
FreeTube: 0.4.1 Beta

**Comment by maricn** [comment]
Same thing, this is a show stopper for me to use the app. Any help would be appreciated.


Addon installed from https://addons.mozilla.org/en-US/firefox/addon/freetube-redirect/:
```
Version
    0.1
Size
    334.89 KB
Last updated
    a year ago (Jun 2, 2018)
```

My env:
```
Firefox: 69.0b16 (64-bit)
macOS: 10.14.6 (18G95)
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
FreeTube: 0.7.0 Beta
```

**Comment by sith-on-mars** [comment]
I have the same issue on Manjaro Linux.

**Comment by kgorol** [comment]
One year later, still not working on my Mac.

**Comment by pqhf5kd** [comment]
Same problem

**Comment by 360fun** [comment]
Now works: https://github.com/FreeTubeApp/FreeTube/issues/618

**Comment by PrestonN** [comment]
This was never a problem with the extension to begin with.  It's a problem with the FreeTube app itself.

Either way, the issue should be fixed now.  You can wait for the next release or download an automated build to get it now.
